threads_num: 10
ignore_errors_num: 2
retries_num: 3
target_dir: "/var/www/nailgun"
working_dir: "/usr/share/fuel-mirror"

# uncomment if need
#   http_proxy: null
#   https_proxy: null
#   fuel_server: 10.20.0.2
#   base_url: http://10.20.0.2:8080
